# This workflow will build and test the macOS app using Xcode
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Xcode Build and Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
      
    - name: Cache derived data
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-xcode-${{ hashFiles('**/*.xcodeproj/project.pbxproj') }}
        restore-keys: |
          ${{ runner.os }}-xcode-
          
    - name: Build app
      run: |
        xcodebuild -project breadcrumbs.xcodeproj \
          -scheme breadcrumbs \
          -configuration Debug \
          -destination 'platform=macOS' \
          build
          
    - name: Run unit tests
      run: |
        xcodebuild -project breadcrumbs.xcodeproj \
          -scheme breadcrumbs \
          -configuration Debug \
          -destination 'platform=macOS' \
          -enableCodeCoverage YES \
          test
          
    - name: Run UI tests
      run: |
        xcodebuild -project breadcrumbs.xcodeproj \
          -scheme breadcrumbs \
          -configuration Debug \
          -destination 'platform=macOS' \
          -testPlan breadcrumbsUITests \
          test
          
    - name: Generate code coverage report
      run: |
        xcrun xccov view --report --json DerivedData/breadcrumbs-*/Logs/Test/*.xcresult > coverage.json
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.json
        flags: xcode
        name: codecov-xcode
        fail_ci_if_error: false
        
    - name: Archive app
      run: |
        xcodebuild -project breadcrumbs.xcodeproj \
          -scheme breadcrumbs \
          -configuration Release \
          -destination 'platform=macOS' \
          archive -archivePath breadcrumbs.xcarchive
          
    - name: Export app
      run: |
        xcodebuild -exportArchive \
          -archivePath breadcrumbs.xcarchive \
          -exportPath ./build \
          -exportOptionsPlist ExportOptions.plist || echo "Export options plist not found, skipping export"

  integration-tests:
    runs-on: macos-latest
    needs: build-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
      
    - name: Run integration tests
      run: |
        xcodebuild -project breadcrumbs.xcodeproj \
          -scheme breadcrumbs \
          -configuration Debug \
          -destination 'platform=macOS' \
          -testPlan breadcrumbsIntegrationTests \
          test || echo "Integration test plan not found, skipping"
          
    - name: Test server functionality
      run: |
        # Test the Vapor server if it's part of the build
        if [ -f "./build/breadcrumbs.app/Contents/MacOS/breadcrumbs" ]; then
          echo "Testing server functionality..."
          # Add server tests here
        fi
